name = "my-app"
compatibility_date = "2023-12-01"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWRmY2MzMzQtNWZjZi00YzE3LWIzMTktZTFmYzlhMjEzMzEyIiwidGVuYW50X2lkIjoiNWFmZGFiMDRmNDdlZTg4ZDRiODE5ZGQzNTQyODRjOGVmM2I3NjM5NTliNDY3MjZkNDkwZDc2OGM0OWE1NjZhYyIsImludGVybmFsX3NlY3JldCI6ImY1YmU0NWJhLTA4ZDAtNDFjMi1hMmU0LTczMWIzNDYxNGQ2ZCJ9.EfEZRZ26HQmhprmnfn0dETQFwhasBKLE_swVudbEDfw"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"